# From images to videos - 3
Now that we understand the connection between images and numpy arrays we can move on to videos! This fits the theme because the temporal dimension of a video extends intuitively to numpy arrays representing a sequence of RGB images. The library we need for this is called open-cv (open source computer vision), and it is imported by calling `import cv2`

Setting up your environment to work with videos can be a bit tricky sometimes because rendering a video relies on GPU code. Try installing open-cv with anaconda by running ` conda install -c conda-forge opencv` in your terminal. If you prefer pip, run `pip install opencv-python`. If you have problems with running the code below google your error message and ask for help from an instructor! 

In [1]:
# we first want to import the library, also import numpy
import cv2 as cv
import numpy as np

The code below uses the open-cv library to read a video from a file and display it. Try executing the cell as it is. You can quit the player by pressing `q`. You don't need to understand each line in detail, but try to understand the general approach behind displaying the video.

In [2]:
# we first create a capture object that reads the video file
capture = cv.VideoCapture('dog_video.mp4')

while True:
    # in an infinite loop, we read frames from the file buffer
    # we get back two values, a True or False value indicating
    # if we actually got a frame, and the frame itself
    got_frame, frame = capture.read()
    
    # because we have a while True loop, we need to have an exit
    # condition. This is handled below
    if not got_frame or cv.waitKey(30) & 0xFF==ord('q'):
        break
    else:
        # if we do get a frame, display it using the imshow function
        cv.imshow('video player', frame)
        # your code goes here

# finally, we always need to close the file reader in video player window
capture.release()
cv.destroyAllWindows()

libGL error: MESA-LOADER: failed to open iris: /home/loaloa/anaconda3/envs/numpy-cv/lib/python3.9/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib64/dri/iris_dri.so) (search paths /usr/lib64/dri, suffix _dri)
libGL error: failed to load driver: iris
libGL error: MESA-LOADER: failed to open swrast: /home/loaloa/anaconda3/envs/numpy-cv/lib/python3.9/site-packages/zmq/backend/cython/../../../../.././libstdc++.so.6: version `GLIBCXX_3.4.30' not found (required by /usr/lib64/dri/swrast_dri.so) (search paths /usr/lib64/dri, suffix _dri)
libGL error: failed to load driver: swrast


In [3]:
# this is simply a function to play a video in numpy format
def play_video(arr):
    for frame_id in range(arr.shape[0]):
        if cv.waitKey(100) & 0xFF==ord('q'):
            break
        else:
            cv.imshow('videoplayer', arr[frame_id])
    cv.destroyAllWindows()

-------------
#### Exercise 0 [Optional]: Record your own video using your webcam. It should not be longer than 8 seconds to limit the computational load. The video could be of your face or something else. Save this video and place it in the same folder where this notebook file is located. Finally, change the filename in the code above from `dog_video.mp4` to your filename. 

#### Exercise 1: Displaying a video is useful for sure, but going foward we want to modify the video frames using numpy. First,  copy the code from above into the cell below. Next, create an empty list above the while loop. Everytime you get a frame, append it to this list. After the loop has finished use the `numpy.stack` function to create one big numpy array. What is the shape of this final array and what do the dimensions refer to? What is the dtype of the array?


In [4]:
# Ex1: your code goes here


In [5]:
# Ex1: solution
capture = cv.VideoCapture('dog_video.mp4')
frame_list = []
while True:
    got_frame, frame = capture.read()
    
    if not got_frame or cv.waitKey(20) & 0xFF==ord('q'):
        break
    else:
        frame_list.append(frame)
capture.release()

arr = np.stack(frame_list)
print(arr.shape) # frame (132), vertical_pixel_id (720), horizontal_pixel (1280), Color (3)
print(arr.dtype) # unsiged integer 8, valid values are integers between 0 and 255. 8 bits.

(132, 720, 1280, 3)
uint8


-------------
#### Exercise 2: With numpy's `.copy()` function make a copy of the original video. In that new video, binarize each RGB channel at the threshold of 60 so that the image contains pixel intensities of 0 and 255. Hint: To do this elgegantly, create the mask by comparing the video array with a 3-element array. What shape does the mask have? Play the video using the `play_video(your_arr)` function defined above and intepret the 8 colors in the video.  

In [6]:
# Ex2: your code goes here 


In [7]:
# Ex2: solution
mask = arr > np.array([60,60,60])
print(mask.shape) # the mask has exactly the same shape as the video. This is different from 
                  # previous masks creating a 1d array after comparing with a scaler.
arr_masked = arr.copy() 
arr_masked[mask] = 255
arr_masked[~mask] = 0

play_video(arr_masked)

# The colors in the video are 3 + 3 + 2, red, green and blue regions, 
# purple, cyan, and yellow, and finally black and white. This derives 
# from 2^3 combinations of binary RGB values. 

(132, 720, 1280, 3)


-------------
#### Exercise 3: Filter your recorded video such that the first 50 frames contain only red colors, everything past that should only have green colors.  Save the result in a new array called `arr_single_col` and check th result by playing it with the cell below. What's the order of red green and blue in the color dimension?

In [8]:
# Ex3: your code goes here 


In [9]:
# Ex3: solution
# in the dog video, RGB are reversed, Blue, Green, Red is the order
arr_single_col = arr.copy()
arr_single_col[:50, :, :, :-1] = 0
print(arr_single_col)
arr_single_col[50:, :, :, 0::2] = 0
print(arr_single_col)

play_video(arr_single_col)

[[[[  0   0  34]
   [  0   0 137]
   [  0   0 123]
   ...
   [  0   0  77]
   [  0   0  87]
   [  0   0  43]]

  [[  0   0  38]
   [  0   0 140]
   [  0   0 125]
   ...
   [  0   0  64]
   [  0   0  77]
   [  0   0  38]]

  [[  0   0  38]
   [  0   0 140]
   [  0   0 125]
   ...
   [  0   0  52]
   [  0   0  70]
   [  0   0  38]]

  ...

  [[  0   0  24]
   [  0   0 108]
   [  0   0 102]
   ...
   [  0   0  83]
   [  0   0  95]
   [  0   0  50]]

  [[  0   0  24]
   [  0   0 107]
   [  0   0 101]
   ...
   [  0   0  83]
   [  0   0  95]
   [  0   0  50]]

  [[  0   0  24]
   [  0   0 107]
   [  0   0 101]
   ...
   [  0   0  83]
   [  0   0  95]
   [  0   0  50]]]


 [[[  0   0  34]
   [  0   0 137]
   [  0   0 123]
   ...
   [  0   0  77]
   [  0   0  87]
   [  0   0  43]]

  [[  0   0  38]
   [  0   0 140]
   [  0   0 125]
   ...
   [  0   0  64]
   [  0   0  77]
   [  0   0  38]]

  [[  0   0  38]
   [  0   0 140]
   [  0   0 125]
   ...
   [  0   0  52]
   [  0   0  70]
   [  0   0

#### Exercise 4: The dog in the video has a brown/ orange colored fur. In RGB values, this color roughly corresbonds to red content between 40-184, green 25-110, and blue 0-50. Create a mask for each color channel, then connect them with a logical AND to set all values in this range to white (255). Again create a copy of the video for this exercise and display it using the `play_video()` function.

In [10]:
# Ex4: your code goes here


In [11]:
# Ex4: solution
arr_single_col = arr.copy()
blue_mask = (arr_single_col[..., 0] >0) & (arr_single_col[..., 0] <50)
green_mask = (arr_single_col[..., 1] >25) & (arr_single_col[..., 0] <119)
red_mask = (arr_single_col[..., 2] >40) & (arr_single_col[..., 0] <184)

arr_dog_segmented = arr.copy()
arr_dog_segmented[red_mask & blue_mask & red_mask] = 255

play_video(arr_dog_segmented)

-------------
#### Open final project: The code below is a boiler plate for using your computers webcam video feed. Play with the `frame_processing()` function to modify the video feed  like in the exercises above. The code now implements an edge detection function, can you think of other cool modifications? Feel free to google other open-cv filters!

In [12]:
def frame_processing(frame):
    frame_gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    frame_edges = cv.Canny(frame_gray, 45, 100)
    return frame_edges

In [13]:
def live_video(camera_id=0, frame_processing_function=frame_processing):
    capture = cv.VideoCapture(0)

    if not capture.isOpened():
        raise IOError("Cannot open webcam")

    while True:
        got_frame, frame = capture.read()
        if not got_frame or cv.waitKey(20) & 0xFF==ord('q'):
            break
        else:
            frame_prcsd = frame_processing_function(frame)
            # print(frame_prcsd.shape)
            cv.imshow('Input', frame_prcsd)

    capture.release()
    cv.destroyAllWindows()

In [14]:
# try a different integer for camera_id if 0 doesn't work
live_video(camera_id=0)

[ WARN:0@33.234] global /opt/conda/conda-bld/opencv-suite_1664548337286/work/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
